### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by CarlosAurelioMRF** [koala-interactive/wowza-webrtc-player#11]
I get window is not defined error.

![image](https://user-images.githubusercontent.com/28075600/110634778-1c494a80-8189-11eb-9462-5bc4beb67d08.png)

**Comment by vthibault** [comment]
Hi @CarlosAurelioMRF !
This library isn't working on node env, only in the browser.

If you are building Universal Rendering App : 
- You should conditionally load it only on browser env by (using `process.browser` + dynamic import ?)
- Or dynamically import it in a useEffect()

**Comment by CarlosAurelioMRF** [comment]
I appreciate your reply, I founded a solution to use on nextjs.

Thanks!
